/**
 * 20명 데모 투자자용 실제 키페어 생성.
 * - 주소 → app/lib/demo-investor-addresses.json (리포 포함 가능)
 * - private key → .env.demo.local (gitignore 대상, 절대 커밋 금지)
 *
 * 실행: cd frontend && npx tsx scripts/generate-demo-wallets.ts
 */
import { generatePrivateKey, privateKeyToAccount } from "viem/accounts";
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = fileURLToPath(new URL(".", import.meta.url));
const ROOT = join(__dirname, "..");
const ADDRESSES_PATH = join(ROOT, "app", "lib", "demo-investor-addresses.json");
const ENV_DEMO_PATH = join(ROOT, ".env.demo.local");

const N = 20;

interface GeneratedWallet {
    index: number;
    address: string;
    privateKey: string;
}

const wallets: GeneratedWallet[] = [];
for (let i = 0; i < N; i++) {
    const privateKey = generatePrivateKey();
    const account = privateKeyToAccount(privateKey as `0x${string}`);
    wallets.push({
        index: i + 1,
        address: account.address,
        privateKey,
    });
}

// 1. 주소만 JSON으로 (리포 커밋 가능)
const addresses = wallets.map((w) => w.address);
writeFileSync(ADDRESSES_PATH, JSON.stringify(addresses, null, 2), "utf-8");
console.log("Written:", ADDRESSES_PATH);

// 2. private key → .env.demo.local (gitignore 필수)
const envLines = [
    "# Demo 20 investors – private keys. DO NOT COMMIT. Add to .gitignore.",
    "# Generated by scripts/generate-demo-wallets.ts",
    "",
    ...wallets.map(
        (w) => `DEMO_INV_${String(w.index).padStart(2, "0")}_PRIVATE_KEY=${w.privateKey}`
    ),
];
writeFileSync(ENV_DEMO_PATH, envLines.join("\n") + "\n", "utf-8");
console.log("Written:", ENV_DEMO_PATH);
console.log("");
console.log("Next:");
console.log("  1. Ensure .env.demo.local is in .gitignore (e.g. .env*.local).");
console.log("  2. Run seed-demo or seed-demo-onchain; demo-investors will use addresses from demo-investor-addresses.json.");
console.log("  3. Fund the 20 addresses with CTC (Discord faucet) and USDC (Faucet or Relayer).");
