// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/bonds": {
    params: {};
  };
  "/portfolio": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/bonds" | "/portfolio" | "/settings" | "/api/auth/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/bonds.tsx": {
    id: "routes/bonds";
    page: "/bonds";
  };
  "routes/portfolio.tsx": {
    id: "routes/portfolio";
    page: "/portfolio";
  };
  "routes/settings.tsx": {
    id: "routes/settings";
    page: "/settings";
  };
  "routes/auth.ts": {
    id: "routes/auth";
    page: "/api/auth/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/bonds": typeof import("./app/routes/bonds.tsx");
  "routes/portfolio": typeof import("./app/routes/portfolio.tsx");
  "routes/settings": typeof import("./app/routes/settings.tsx");
  "routes/auth": typeof import("./app/routes/auth.ts");
};